// Code generated by goyacc -o yysmi.go -p smi smi.y. DO NOT EDIT.

//line smi.y:43

package smi

import __yyfmt__ "fmt"

//line smi.y:44

//line smi.y:57
type smiSymType struct {
	yys                  int
	text                 string
	id                   string
	err                  int
	date                 string
	objectPtr            string
	SmiStatus            int
	SmiAccess            int
	typePtr              string
	listPtr              string
	namedNumberPtr       string
	rangePtr             string
	valuePtr             string
	unsigned32           uint32
	integer32            int32
	unsigned64           uint64
	integer64            int64
	compl                string
	index                string
	modulePtr            string
	subjectCategoriesPtr string
	subid                SubID
	subidList            []SubID
	node                 Node
	nodeList             []Node
	idList               []string
	imp                  Import
	impList              []Import
}

const tDOT_DOT = 57346
const tCOLON_COLON_EQUAL = 57347
const tUPPERCASE_IDENTIFIER = 57348
const tLOWERCASE_IDENTIFIER = 57349
const tNUMBER = 57350
const tNEGATIVENUMBER = 57351
const tNUMBER64 = 57352
const tNEGATIVENUMBER64 = 57353
const tBIN_STRING = 57354
const tHEX_STRING = 57355
const tQUOTED_STRING = 57356
const tACCESS = 57357
const tAGENT_CAPABILITIES = 57358
const tAPPLICATION = 57359
const tAUGMENTS = 57360
const tBEGIN_ = 57361
const tBITS = 57362
const tCHOICE = 57363
const tCONTACT_INFO = 57364
const tCREATION_REQUIRES = 57365
const tCOUNTER32 = 57366
const tCOUNTER64 = 57367
const tDEFINITIONS = 57368
const tDEFVAL = 57369
const tDESCRIPTION = 57370
const tDISPLAY_HINT = 57371
const tEND = 57372
const tENTERPRISE = 57373
const tEXPORTS = 57374
const tEXTENDS = 57375
const tFROM = 57376
const tGROUP = 57377
const tGAUGE32 = 57378
const tIDENTIFIER = 57379
const tIMPLICIT = 57380
const tIMPLIED = 57381
const tIMPORTS = 57382
const tINCLUDES = 57383
const tINDEX = 57384
const tINSTALL_ERRORS = 57385
const tINTEGER = 57386
const tINTEGER32 = 57387
const tINTEGER64 = 57388
const tIPADDRESS = 57389
const tLAST_UPDATED = 57390
const tMACRO = 57391
const tMANDATORY_GROUPS = 57392
const tMAX_ACCESS = 57393
const tMIN_ACCESS = 57394
const tMODULE = 57395
const tMODULE_COMPLIANCE = 57396
const tMODULE_IDENTITY = 57397
const tNOT_ACCESSIBLE = 57398
const tNOTIFICATIONS = 57399
const tNOTIFICATION_GROUP = 57400
const tNOTIFICATION_TYPE = 57401
const tOBJECT = 57402
const tOBJECT_GROUP = 57403
const tOBJECT_IDENTITY = 57404
const tOBJECT_TYPE = 57405
const tOBJECTS = 57406
const tOCTET = 57407
const tOF = 57408
const tORGANIZATION = 57409
const tOPAQUE = 57410
const tPIB_ACCESS = 57411
const tPIB_DEFINITIONS = 57412
const tPIB_INDEX = 57413
const tPIB_MIN_ACCESS = 57414
const tPIB_REFERENCES = 57415
const tPIB_TAG = 57416
const tPOLICY_ACCESS = 57417
const tPRODUCT_RELEASE = 57418
const tREFERENCE = 57419
const tREVISION = 57420
const tSEQUENCE = 57421
const tSIZE = 57422
const tSTATUS = 57423
const tSTRING = 57424
const tSUBJECT_CATEGORIES = 57425
const tSUPPORTS = 57426
const tSYNTAX = 57427
const tTEXTUAL_CONVENTION = 57428
const tTIMETICKS = 57429
const tTRAP_TYPE = 57430
const tUNIQUENESS = 57431
const tUNITS = 57432
const tUNIVERSAL = 57433
const tUNSIGNED32 = 57434
const tUNSIGNED64 = 57435
const tVALUE = 57436
const tVARIABLES = 57437
const tVARIATION = 57438
const tWRITE_SYNTAX = 57439

var smiToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tDOT_DOT",
	"tCOLON_COLON_EQUAL",
	"tUPPERCASE_IDENTIFIER",
	"tLOWERCASE_IDENTIFIER",
	"tNUMBER",
	"tNEGATIVENUMBER",
	"tNUMBER64",
	"tNEGATIVENUMBER64",
	"tBIN_STRING",
	"tHEX_STRING",
	"tQUOTED_STRING",
	"tACCESS",
	"tAGENT_CAPABILITIES",
	"tAPPLICATION",
	"tAUGMENTS",
	"tBEGIN_",
	"tBITS",
	"tCHOICE",
	"tCONTACT_INFO",
	"tCREATION_REQUIRES",
	"tCOUNTER32",
	"tCOUNTER64",
	"tDEFINITIONS",
	"tDEFVAL",
	"tDESCRIPTION",
	"tDISPLAY_HINT",
	"tEND",
	"tENTERPRISE",
	"tEXPORTS",
	"tEXTENDS",
	"tFROM",
	"tGROUP",
	"tGAUGE32",
	"tIDENTIFIER",
	"tIMPLICIT",
	"tIMPLIED",
	"tIMPORTS",
	"tINCLUDES",
	"tINDEX",
	"tINSTALL_ERRORS",
	"tINTEGER",
	"tINTEGER32",
	"tINTEGER64",
	"tIPADDRESS",
	"tLAST_UPDATED",
	"tMACRO",
	"tMANDATORY_GROUPS",
	"tMAX_ACCESS",
	"tMIN_ACCESS",
	"tMODULE",
	"tMODULE_COMPLIANCE",
	"tMODULE_IDENTITY",
	"tNOT_ACCESSIBLE",
	"tNOTIFICATIONS",
	"tNOTIFICATION_GROUP",
	"tNOTIFICATION_TYPE",
	"tOBJECT",
	"tOBJECT_GROUP",
	"tOBJECT_IDENTITY",
	"tOBJECT_TYPE",
	"tOBJECTS",
	"tOCTET",
	"tOF",
	"tORGANIZATION",
	"tOPAQUE",
	"tPIB_ACCESS",
	"tPIB_DEFINITIONS",
	"tPIB_INDEX",
	"tPIB_MIN_ACCESS",
	"tPIB_REFERENCES",
	"tPIB_TAG",
	"tPOLICY_ACCESS",
	"tPRODUCT_RELEASE",
	"tREFERENCE",
	"tREVISION",
	"tSEQUENCE",
	"tSIZE",
	"tSTATUS",
	"tSTRING",
	"tSUBJECT_CATEGORIES",
	"tSUPPORTS",
	"tSYNTAX",
	"tTEXTUAL_CONVENTION",
	"tTIMETICKS",
	"tTRAP_TYPE",
	"tUNIQUENESS",
	"tUNITS",
	"tUNIVERSAL",
	"tUNSIGNED32",
	"tUNSIGNED64",
	"tVALUE",
	"tVARIABLES",
	"tVARIATION",
	"tWRITE_SYNTAX",
	"'{'",
	"'}'",
	"';'",
	"','",
	"'('",
	"')'",
	"'['",
	"']'",
	"'.'",
	"'|'",
}
var smiStatenames = [...]string{}

const smiEofCode = 1
const smiErrCode = 2
const smiInitialStackSize = 16

//line smi.y:1923

//line yacctab:1
var smiExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 28,
	30, 52,
	-2, 0,
	-1, 33,
	30, 51,
	-2, 0,
	-1, 50,
	16, 374,
	54, 339,
	58, 335,
	61, 331,
	-2, 83,
	-1, 52,
	5, 88,
	-2, 84,
	-1, 158,
	98, 190,
	102, 188,
	-2, 187,
	-1, 159,
	102, 193,
	-2, 192,
	-1, 160,
	98, 195,
	106, 50,
	-2, 109,
	-1, 169,
	102, 225,
	-2, 224,
	-1, 193,
	106, 50,
	-2, 195,
	-1, 202,
	102, 201,
	-2, 200,
}

const smiPrivate = 57344

const smiLast = 801

var smiAct = [...]int{

	282, 675, 448, 564, 618, 591, 642, 354, 612, 232,
	629, 595, 583, 146, 585, 560, 527, 447, 12, 536,
	502, 480, 233, 469, 348, 366, 424, 177, 365, 277,
	274, 259, 258, 256, 249, 229, 237, 230, 152, 81,
	208, 209, 155, 211, 161, 4, 160, 4, 201, 415,
	311, 662, 210, 312, 312, 320, 319, 589, 440, 439,
	150, 151, 438, 404, 167, 172, 608, 602, 603, 604,
	605, 606, 607, 609, 212, 27, 168, 160, 200, 678,
	651, 679, 127, 553, 158, 159, 173, 166, 621, 391,
	622, 150, 614, 372, 615, 167, 172, 575, 219, 576,
	163, 551, 442, 552, 443, 162, 313, 168, 171, 408,
	406, 409, 295, 125, 299, 158, 159, 173, 166, 165,
	342, 321, 343, 322, 109, 214, 147, 170, 308, 200,
	309, 163, 169, 174, 22, 294, 162, 295, 650, 171,
	633, 647, 298, 646, 164, 645, 632, 179, 624, 128,
	165, 588, 587, 577, 569, 554, 533, 600, 170, 532,
	531, 477, 476, 169, 174, 462, 458, 345, 144, 297,
	619, 251, 143, 206, 112, 164, 20, 672, 597, 581,
	580, 578, 567, 550, 231, 548, 542, 541, 524, 510,
	509, 497, 192, 496, 495, 449, 446, 429, 426, 394,
	303, 301, 198, 212, 223, 207, 190, 183, 228, 213,
	215, 217, 181, 199, 220, 221, 222, 8, 643, 347,
	227, 204, 546, 131, 218, 592, 489, 133, 292, 503,
	137, 382, 202, 280, 281, 198, 252, 326, 254, 253,
	427, 255, 369, 306, 268, 305, 199, 302, 307, 271,
	300, 325, 243, 180, 132, 334, 339, 257, 279, 261,
	260, 263, 262, 265, 264, 481, 349, 335, 244, 79,
	398, 304, 636, 507, 351, 329, 330, 340, 333, 296,
	240, 135, 138, 10, 539, 114, 139, 242, 508, 288,
	140, 332, 637, 470, 356, 205, 331, 358, 231, 338,
	193, 474, 182, 516, 231, 142, 522, 119, 316, 540,
	315, 118, 563, 367, 116, 117, 30, 377, 337, 317,
	318, 376, 383, 336, 341, 287, 506, 11, 361, 203,
	363, 257, 130, 357, 370, 359, 26, 362, 158, 159,
	224, 245, 110, 291, 371, 373, 375, 374, 126, 290,
	396, 34, 247, 378, 163, 18, 17, 16, 15, 162,
	400, 401, 677, 653, 590, 530, 460, 379, 450, 410,
	380, 381, 436, 390, 384, 385, 386, 387, 388, 413,
	389, 402, 407, 405, 393, 111, 368, 49, 584, 293,
	225, 565, 49, 668, 422, 403, 23, 425, 261, 260,
	263, 262, 265, 264, 431, 141, 432, 666, 433, 283,
	234, 14, 419, 420, 437, 649, 631, 421, 659, 367,
	18, 17, 16, 416, 417, 21, 630, 631, 572, 456,
	414, 360, 270, 269, 24, 670, 444, 454, 434, 658,
	355, 528, 178, 412, 278, 275, 425, 250, 238, 461,
	520, 464, 487, 272, 266, 445, 5, 579, 517, 367,
	453, 475, 492, 484, 483, 482, 441, 430, 395, 175,
	457, 129, 19, 314, 673, 463, 465, 466, 3, 661,
	472, 6, 543, 471, 187, 123, 558, 557, 498, 435,
	186, 122, 485, 452, 185, 121, 488, 499, 490, 451,
	184, 493, 120, 504, 494, 512, 513, 514, 511, 547,
	525, 523, 344, 216, 267, 197, 196, 195, 194, 353,
	529, 352, 518, 491, 566, 428, 399, 289, 176, 115,
	544, 555, 310, 455, 189, 113, 191, 188, 124, 31,
	9, 473, 549, 526, 545, 610, 611, 236, 235, 136,
	397, 561, 562, 350, 674, 556, 667, 669, 665, 641,
	640, 574, 594, 519, 501, 500, 568, 573, 570, 571,
	586, 45, 635, 638, 538, 537, 535, 534, 559, 515,
	486, 468, 467, 42, 613, 44, 561, 586, 596, 43,
	627, 617, 593, 625, 13, 364, 241, 239, 134, 616,
	623, 479, 478, 628, 626, 598, 620, 582, 521, 505,
	226, 246, 411, 418, 276, 328, 157, 327, 586, 601,
	599, 324, 149, 145, 35, 41, 40, 286, 634, 284,
	285, 392, 596, 639, 644, 423, 613, 346, 648, 459,
	39, 38, 652, 37, 654, 655, 657, 248, 656, 323,
	273, 156, 154, 36, 660, 83, 82, 153, 54, 65,
	66, 53, 48, 148, 51, 100, 46, 663, 664, 87,
	25, 671, 33, 101, 102, 676, 32, 78, 680, 77,
	29, 681, 676, 28, 86, 103, 85, 84, 80, 7,
	2, 1, 0, 0, 88, 107, 89, 0, 0, 90,
	0, 0, 0, 91, 92, 0, 0, 104, 105, 47,
	93, 94, 95, 52, 50, 0, 0, 96, 0, 0,
	0, 0, 0, 64, 0, 0, 0, 0, 0, 0,
	0, 74, 76, 0, 0, 97, 98, 106, 0, 0,
	0, 99, 108, 75, 0, 0, 0, 0, 0, 0,
	0, 0, 72, 67, 69, 0, 0, 0, 0, 0,
	0, 63, 55, 0, 0, 62, 58, 0, 61, 59,
	56, 0, 0, 0, 0, 71, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 60, 70, 57, 0, 0, 0, 73,
	68,
}
var smiPact = [...]int{

	450, -1000, 450, -1000, 119, -1000, -1000, 257, 414, 467,
	-1000, -1000, 77, 414, -1000, -1000, -1000, 32, -1000, 377,
	-1000, -1000, 426, 304, -28, 276, -1000, -1000, 707, -1000,
	649, 24, 312, 707, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 75, -1000, 225,
	252, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 13, 649, -1000,
	48, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 466, 295, 135, 173, 142, 217, 147,
	221, 228, 236, 389, 256, -1000, -1000, 450, 649, 40,
	464, -1000, 435, 71, 172, 114, 254, 109, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	108, -1000, -1000, 294, -1000, -1000, -1000, -1000, -1000, -1000,
	27, -58, 150, 292, 204, 107, -24, 23, 23, -1000,
	-24, -4, 23, 23, 23, 106, 309, 362, -1000, 130,
	435, 414, 396, 441, 216, 230, 171, 192, 311, 323,
	440, 72, -1000, 27, 23, 105, 23, 105, -1000, -1000,
	251, 448, -1000, -24, 425, 424, 447, 438, -1000, -1000,
	-1000, -1000, 437, -1000, 390, -1000, 23, -1000, -1000, 177,
	-1000, -1000, -1000, 414, 414, 395, 274, 395, 361, 36,
	-1000, -1000, -1000, 212, -1000, 70, 41, -1000, 12, 169,
	103, 166, 102, 435, 395, -1000, 162, 395, 29, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -53, 4, -1000, 469,
	-1000, -1000, -1000, -1000, -1000, -1000, -24, -4, -1000, -49,
	-50, -1000, -1000, 22, -1000, 231, 21, -1000, -1000, -1000,
	68, 124, 189, -1000, 201, -1000, -1000, -1000, -1000, 433,
	-1000, -1000, -1000, 395, -1000, 414, 395, -1000, 441, 423,
	435, 414, 435, 414, 358, 161, 435, -1000, -1000, 440,
	-9, -1000, 390, 390, 390, -1000, -1000, -1000, -1000, 283,
	279, -1000, 438, -1000, -1000, -1000, -24, -1000, -1000, -24,
	-24, 149, 285, -24, -24, -24, -24, -24, -1000, -24,
	-1000, -1000, -1000, 437, -13, -1000, 356, 101, 463, 395,
	196, -1000, 433, 433, -1000, -1000, 189, -1000, 373, -1000,
	-40, 355, 11, 354, 10, -1000, -1000, -1000, 395, 436,
	351, -1000, 422, -1000, -54, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -24, -24, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 404, 189, 395, 414, 100, -1000, 159, -1000, 99,
	-1000, -1000, 462, 395, -1000, 395, -1000, 395, -1000, 414,
	-1000, 344, -1000, 395, -41, -44, -1000, -1000, -45, -1000,
	-1000, 461, -1000, 3, -1000, -1000, 414, 435, 98, 414,
	97, 340, -1000, -1000, -1000, 189, 395, -1000, -1000, -1000,
	-1000, 421, -1000, 414, 67, 338, 414, 66, -1000, 414,
	395, 189, 189, 240, -1000, 189, -1000, -1000, -1000, 258,
	395, 63, -1000, 62, 187, 460, 459, 458, 240, -1000,
	446, 189, 141, 189, -1000, -1000, -1000, -1000, 457, 187,
	-1000, 396, 96, 95, 93, -1000, -1000, 414, 145, 71,
	255, 92, 91, -1000, -1000, 414, 414, 414, 253, -1000,
	453, 145, -1000, 444, -1000, 264, -1000, 90, -1000, 434,
	414, 337, 61, 60, 57, 249, 89, 88, -1000, -1000,
	414, 133, -1000, 87, 414, 85, 2, -1000, -19, 56,
	395, -1000, -1000, -1000, -1000, 249, -1000, -1000, -1000, -1000,
	-1000, 414, 414, 271, -1000, 364, -1000, 84, 414, 55,
	414, -1000, 434, 420, -1000, -1000, -1000, 414, 414, -2,
	-1000, -1000, 54, 83, 452, 82, 81, 349, 53, -1000,
	52, -1000, -46, 336, 140, -1000, 414, -1000, 414, 80,
	59, 414, -7, -1000, 414, -1000, -1000, -1000, -1000, -1000,
	395, 73, 71, -1000, -11, -1000, -1000, 414, 49, -1000,
	419, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	47, 39, -1000, -1000, -1000, 349, -1000, -1000, 220, 71,
	-1000, 122, 414, 46, -1000, 44, 42, 408, 37, -1000,
	-22, -1000, -1000, 414, -1000, 335, 433, 433, -1000, -1000,
	-1000, 122, -1000, 414, -1000, -1000, -1000, -1000, -1000, -22,
	432, 410, -1000, 395, -1000, -1000, -1000, -1000, -1000, -52,
	-1000, 140, -1000, 73, 392, 370, 428, 364, 79, -1000,
	-1000, -1000, 414, 334, -20, -1000, -1000, 395, -1000, 414,
	-1000, -1000,
}
var smiPgo = [...]int{

	0, 691, 690, 478, 689, 44, 39, 688, 687, 686,
	684, 683, 680, 679, 677, 269, 676, 672, 351, 670,
	666, 664, 663, 662, 661, 660, 659, 658, 657, 358,
	653, 652, 42, 651, 650, 30, 13, 649, 647, 34,
	643, 641, 640, 639, 637, 635, 26, 631, 630, 629,
	627, 626, 625, 624, 623, 622, 621, 620, 38, 619,
	617, 616, 615, 40, 41, 52, 33, 32, 31, 43,
	614, 29, 613, 27, 612, 611, 610, 7, 609, 608,
	607, 12, 14, 17, 3, 605, 604, 603, 2, 25,
	24, 602, 601, 21, 598, 597, 35, 37, 596, 595,
	28, 0, 22, 9, 594, 411, 593, 590, 10, 589,
	585, 583, 582, 581, 23, 580, 579, 578, 15, 577,
	576, 19, 575, 574, 5, 4, 573, 572, 571, 565,
	564, 20, 563, 562, 11, 560, 559, 6, 558, 557,
	556, 554, 1, 553, 550, 549, 548, 547, 36, 8,
	546, 545, 544, 16, 543, 541, 540, 539, 538, 537,
	536, 535, 534, 533, 532, 529, 528, 527, 526, 525,
	524, 523, 521, 519, 518, 517, 516, 515, 514, 513,
	512, 511, 510, 509, 508, 502, 500, 499, 495, 494,
	493, 491, 490, 489, 488, 487, 486, 485, 484, 483,
	482, 479, 474,
}
var smiR1 = [...]int{

	0, 1, 1, 2, 2, 3, 4, 4, 156, 156,
	11, 11, 12, 19, 157, 19, 13, 13, 14, 14,
	15, 7, 7, 6, 6, 6, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	8, 9, 9, 9, 9, 9, 9, 9, 10, 10,
	5, 16, 16, 17, 17, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 158, 159,
	20, 21, 21, 21, 21, 21, 21, 21, 21, 21,
	21, 160, 22, 29, 29, 30, 161, 53, 23, 23,
	23, 24, 24, 26, 26, 26, 26, 26, 25, 25,
	25, 27, 27, 54, 162, 163, 54, 54, 31, 32,
	33, 34, 34, 35, 36, 36, 37, 37, 37, 38,
	38, 164, 39, 40, 41, 43, 43, 165, 166, 42,
	44, 44, 45, 45, 46, 47, 47, 49, 49, 49,
	50, 167, 167, 168, 143, 143, 169, 144, 144, 170,
	152, 152, 151, 151, 150, 150, 149, 171, 155, 155,
	154, 154, 153, 172, 48, 173, 48, 51, 52, 145,
	145, 146, 147, 147, 148, 148, 55, 55, 55, 55,
	55, 55, 28, 28, 56, 56, 57, 58, 174, 58,
	175, 58, 58, 176, 58, 177, 58, 58, 58, 58,
	58, 178, 58, 58, 58, 58, 59, 59, 59, 59,
	59, 59, 59, 59, 59, 60, 60, 60, 60, 61,
	61, 61, 61, 61, 61, 179, 61, 61, 61, 61,
	61, 61, 61, 61, 61, 61, 62, 62, 62, 62,
	62, 62, 62, 62, 62, 63, 63, 63, 63, 64,
	65, 66, 66, 67, 67, 68, 68, 68, 68, 68,
	68, 69, 70, 70, 180, 71, 72, 72, 73, 74,
	75, 75, 76, 76, 77, 181, 78, 78, 182, 78,
	78, 183, 79, 79, 80, 80, 81, 81, 82, 83,
	84, 84, 85, 85, 86, 86, 87, 87, 88, 89,
	90, 90, 91, 91, 92, 92, 184, 93, 94, 94,
	95, 96, 96, 97, 98, 99, 99, 100, 101, 102,
	103, 104, 104, 105, 105, 105, 106, 107, 107, 108,
	108, 185, 186, 187, 109, 188, 189, 190, 110, 191,
	192, 193, 111, 112, 113, 113, 194, 114, 115, 115,
	115, 116, 116, 117, 117, 118, 119, 119, 120, 120,
	121, 121, 195, 122, 196, 123, 124, 124, 125, 125,
	126, 127, 127, 127, 197, 198, 199, 128, 129, 129,
	130, 130, 200, 131, 133, 133, 134, 132, 132, 135,
	135, 136, 136, 201, 202, 137, 138, 138, 139, 140,
	140, 141, 141, 142,
}
var smiR2 = [...]int{

	0, 1, 0, 1, 2, 9, 3, 0, 1, 1,
	1, 0, 3, 0, 0, 3, 1, 0, 1, 2,
	3, 1, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 0, 0,
	5, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 3, 1, 1, 7, 0, 4, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 0, 0, 11, 1, 3, 1,
	4, 1, 3, 2, 1, 4, 1, 1, 2, 1,
	3, 0, 5, 11, 21, 0, 2, 0, 0, 11,
	4, 0, 1, 3, 1, 2, 0, 1, 1, 0,
	2, 1, 1, 0, 5, 0, 0, 5, 0, 0,
	5, 0, 1, 0, 1, 3, 1, 0, 5, 0,
	1, 3, 4, 0, 3, 0, 3, 12, 16, 4,
	0, 1, 1, 3, 1, 4, 1, 2, 1, 1,
	1, 1, 5, 5, 1, 1, 1, 1, 0, 3,
	0, 3, 1, 0, 3, 0, 3, 4, 2, 4,
	2, 0, 4, 2, 4, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 2, 2, 3, 3, 2,
	1, 2, 1, 2, 1, 0, 3, 2, 1, 2,
	1, 2, 1, 2, 1, 2, 2, 2, 2, 2,
	2, 1, 2, 1, 1, 1, 1, 1, 0, 3,
	6, 1, 3, 1, 3, 1, 1, 1, 1, 1,
	1, 3, 1, 3, 0, 5, 1, 1, 1, 1,
	2, 0, 2, 0, 1, 0, 5, 4, 0, 5,
	0, 0, 5, 0, 1, 3, 2, 1, 1, 1,
	4, 0, 1, 3, 1, 0, 1, 3, 1, 1,
	2, 0, 1, 0, 1, 2, 0, 5, 4, 0,
	4, 1, 3, 1, 4, 1, 3, 1, 1, 1,
	1, 1, 2, 1, 1, 4, 1, 1, 2, 4,
	1, 0, 0, 0, 15, 0, 0, 0, 15, 0,
	0, 0, 15, 1, 1, 2, 0, 5, 2, 1,
	0, 4, 0, 1, 3, 1, 1, 0, 1, 2,
	1, 1, 0, 5, 0, 8, 2, 0, 2, 0,
	1, 2, 2, 0, 0, 0, 0, 17, 1, 0,
	1, 2, 0, 8, 1, 3, 1, 2, 1, 1,
	0, 1, 2, 0, 0, 11, 2, 0, 1, 4,
	0, 1, 3, 1,
}
var smiChk = [...]int{

	-1000, -1, -2, -3, -5, 6, -3, -4, 98, -156,
	26, 70, -103, -104, -105, -29, 8, 7, 6, 5,
	99, -105, 102, 19, 8, -19, 32, 103, -11, -12,
	40, -157, -16, -17, -18, -53, -30, -40, -41, -42,
	-51, -52, -111, -109, -110, -128, -20, 2, -23, -29,
	7, -21, 6, -24, -27, 55, 63, 88, 59, 62,
	86, 61, 58, 54, 16, -26, -25, 46, 93, 47,
	87, 68, 45, 92, 24, 36, 25, -13, -14, -15,
	-7, -6, 7, 6, -8, -9, -10, 20, 45, 47,
	50, 54, 55, 61, 62, 63, 68, 86, 87, 92,
	16, 24, 25, 36, 58, 59, 88, 46, 93, 100,
	30, -18, 99, -161, 60, -165, 62, 63, 59, 55,
	-185, -188, -191, -197, -158, 100, -15, 34, 101, 5,
	37, 88, 81, 85, -94, 64, -145, 83, 61, 58,
	54, 16, 49, -5, -6, -54, -36, 86, -22, -55,
	20, 21, -58, -28, -31, -32, -33, -61, 44, 45,
	6, -5, 65, 60, 104, 79, 47, 24, 36, 92,
	87, 68, 25, 46, 93, 5, -166, -73, 7, -36,
	81, 98, 48, 98, -186, -189, -192, -198, -159, -162,
	98, -160, -58, 6, -174, -175, -176, -177, -64, -65,
	102, 106, 82, 37, 17, 91, 66, 98, -63, -64,
	-65, -69, 98, -64, 102, -64, -179, -63, -65, 102,
	-64, -64, -64, 98, 31, 28, -76, 90, -73, -96,
	-97, -88, -103, -102, 14, -146, -147, -148, 7, -95,
	64, -98, 57, 81, 76, 30, -75, 29, -38, -39,
	7, 99, -64, -69, -64, -69, -66, 80, -67, -68,
	9, 8, 11, 10, 13, 12, 6, -178, -63, 8,
	8, -32, 6, -34, -35, 7, -70, -71, 7, -64,
	-103, -103, -101, 14, -49, -48, -50, 51, 15, -167,
	75, 69, -101, 28, 99, 101, 67, 99, 101, 102,
	81, 98, 81, 98, -73, -101, 81, -101, 99, 101,
	-164, 103, 107, 102, 4, -69, -64, -65, -65, 105,
	105, 99, 101, -37, -56, 20, 6, -60, -62, 44,
	45, 65, 60, 47, 24, 36, 92, 87, 68, 25,
	46, 93, 99, 101, -180, 99, -44, 95, -90, 77,
	-143, 73, -172, -173, -77, 7, -101, -97, -101, -148,
	8, -73, -96, -73, -99, -100, -89, -103, 28, 81,
	-73, -39, 102, -67, -66, -68, 38, 38, -35, -63,
	-63, -63, 82, 37, -63, -63, -63, -63, -63, -63,
	-71, 102, -47, 28, 98, 5, -101, -144, 74, -168,
	-77, -77, -90, 22, 103, 28, 99, 28, 99, 101,
	-101, -74, 7, 28, 8, 103, -63, -63, -72, 8,
	9, -90, -101, -45, -46, -88, 98, 81, -169, 98,
	5, -101, -101, -101, -100, -193, 28, -101, 103, 103,
	103, 5, 99, 101, -103, -73, 98, -83, -88, 98,
	28, -187, -190, -90, -101, -163, 8, -46, 99, -43,
	28, -88, 99, -89, -101, -90, -90, -112, -113, -114,
	53, -199, -90, -155, 43, -101, 99, 99, -91, -92,
	-93, 78, 5, 5, 5, -114, -115, 6, -90, 85,
	-90, -171, 5, -93, -102, 98, 98, 98, -194, -103,
	-129, -130, -131, 84, -36, -78, 71, 18, 33, 98,
	98, -184, -103, -103, -103, -116, 50, 5, -131, -132,
	6, -79, 42, -181, 98, -182, -154, -153, 7, -103,
	28, 99, 99, 99, -119, -120, -121, -122, -123, 35,
	60, 98, 98, -200, -103, -152, 89, -183, 98, -83,
	98, 99, 101, 102, 99, -101, -121, -195, -196, -117,
	-118, -103, -103, 41, -84, 27, -170, 98, -83, 99,
	-83, -153, 8, -103, -88, 99, 101, 99, 98, 5,
	98, 98, -80, -81, 39, -82, -88, 99, 99, 103,
	28, -124, 85, -118, -133, -134, -103, 98, -85, -57,
	98, -59, 8, 9, 10, 11, 12, 13, 7, 14,
	-151, -150, -149, -88, 99, 101, -82, -101, -125, 97,
	-36, 99, 101, -88, 99, -106, -86, -107, -87, -108,
	7, 8, 99, 101, -81, -127, 52, 72, -126, -36,
	-135, -136, -137, 96, -134, 99, 99, 99, -108, 7,
	101, 102, -149, 28, -77, -77, -137, -88, 7, 8,
	-101, -201, 103, -124, -125, -138, 15, -140, 23, -139,
	7, -84, 98, -202, -141, -142, -88, 28, 99, 101,
	-101, -142,
}
var smiDef = [...]int{

	2, -2, 1, 3, 7, 50, 4, 0, 0, 0,
	8, 9, 0, 320, 321, 323, 324, 83, 84, 0,
	6, 322, 0, 13, 0, 11, 14, 325, -2, 10,
	17, 0, 0, -2, 53, 55, 56, 57, 58, 59,
	60, 61, 62, 63, 64, 65, 66, 0, 86, 127,
	-2, 68, -2, 89, 90, 71, 72, 73, 74, 75,
	76, 77, 78, 79, 80, 91, 92, 101, 102, 93,
	94, 95, 96, 97, 98, 99, 100, 0, 16, 18,
	0, 21, 23, 24, 25, 26, 27, 28, 29, 30,
	31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
	41, 42, 43, 44, 45, 46, 47, 48, 49, 15,
	5, 54, 67, 0, 0, 0, 0, 0, 309, 170,
	0, 0, 0, 0, 0, 12, 19, 0, 0, 0,
	0, 128, 0, 0, 0, 0, 0, 0, 332, 336,
	340, 375, 69, 20, 22, 87, 103, 104, 107, 114,
	0, 81, 176, 0, 178, 179, 180, 181, -2, -2,
	-2, 0, 0, 0, 0, 0, 248, 220, 222, -2,
	248, 228, 230, 232, 234, 0, 0, 0, 268, 273,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 271,
	0, 0, 177, -2, 0, 0, 0, 0, 198, 203,
	0, 0, -2, 248, 0, 0, 0, 0, 219, 245,
	246, 247, 0, 221, 0, 223, 0, 227, 229, 0,
	231, 233, 235, 0, 0, 0, 139, 0, 0, 0,
	311, 313, 298, 0, 319, 0, 171, 172, 174, 0,
	0, 0, 0, 0, 0, 70, 0, 0, 0, 119,
	121, 82, 189, 191, 194, 196, 0, 0, 251, 253,
	255, 256, 257, 258, 259, 260, 0, 0, 205, 0,
	0, 108, 109, 0, 111, 0, 0, 262, 264, 226,
	0, 131, 301, 318, 145, 137, 138, 163, 165, 0,
	141, 142, 272, 0, 308, 0, 0, 169, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 270, 115, 0,
	0, 249, 0, 0, 0, 197, 199, 204, 202, 0,
	0, 110, 0, 113, 116, 117, 248, 184, 185, 248,
	248, 0, 0, 248, 248, 248, 248, 248, 241, 248,
	243, 244, 261, 0, 0, 85, 136, 0, 0, 0,
	148, 143, 0, 0, 140, 274, 301, 312, 0, 173,
	0, 0, 0, 0, 0, 315, 317, 299, 0, 0,
	0, 120, 0, 252, 0, 254, 182, 183, 112, 118,
	215, 216, 248, 248, 236, 237, 238, 239, 240, 242,
	263, 0, 301, 0, 0, 0, 300, 0, 146, 0,
	164, 166, 0, 0, 175, 0, 310, 0, 314, 0,
	341, 0, 269, 0, 0, 0, 217, 218, 0, 266,
	267, 0, 135, 0, 132, 134, 0, 0, 0, 0,
	0, 0, 333, 337, 316, 301, 0, 105, 122, 250,
	265, 0, 130, 0, 0, 125, 0, 0, 289, 0,
	0, 301, 301, 0, 376, 301, 129, 133, 123, 159,
	0, 0, 144, 0, 303, 0, 0, 0, 343, 344,
	350, 301, 0, 301, 157, 126, 147, 167, 0, 302,
	304, 0, 0, 0, 0, 345, 346, 349, 379, 0,
	280, 0, 0, 305, 306, 0, 0, 0, 352, 348,
	0, 378, 380, 0, 106, 283, 275, 0, 278, 0,
	0, 0, 0, 0, 0, 357, 0, 0, 381, 382,
	388, 151, 281, 0, 0, 0, 0, 160, 0, 0,
	0, 334, 338, 342, 347, 356, 358, 360, 361, 362,
	364, 0, 0, 0, 387, 291, 149, 0, 0, 0,
	0, 158, 0, 0, 168, 307, 359, 0, 0, 0,
	353, 355, 0, 0, 0, 0, 0, 0, 0, 277,
	0, 161, 0, 0, 367, 351, 0, 377, 0, 0,
	0, 153, 0, 284, 0, 287, 288, 276, 279, 162,
	0, 369, 0, 354, 0, 384, 386, 0, 0, 292,
	295, 186, 206, 207, 208, 209, 210, 211, 212, 213,
	0, 152, 154, 156, 282, 0, 286, 363, 373, 0,
	366, 390, 0, 0, 290, 0, 0, 326, 294, 327,
	296, 330, 150, 0, 285, 0, 0, 0, 368, 370,
	383, 389, 391, 0, 385, 124, 214, 293, 328, 0,
	0, 0, 155, 0, 371, 372, 392, 393, 297, 0,
	365, 367, 329, 369, 397, 400, 0, 291, 0, 396,
	398, 394, 0, 0, 0, 401, 403, 0, 399, 0,
	395, 402,
}
var smiTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	102, 103, 3, 3, 101, 3, 106, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 100,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 104, 3, 105, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 98, 107, 99,
}
var smiTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97,
}
var smiTok3 = [...]int{
	0,
}

var smiErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	smiDebug        = 0
	smiErrorVerbose = false
)

type smiLexer interface {
	Lex(lval *smiSymType) int
	Error(s string)
}

type smiParser interface {
	Parse(smiLexer) int
	Lookahead() int
}

type smiParserImpl struct {
	lval  smiSymType
	stack [smiInitialStackSize]smiSymType
	char  int
}

func (p *smiParserImpl) Lookahead() int {
	return p.char
}

func smiNewParser() smiParser {
	return &smiParserImpl{}
}

const smiFlag = -1000

func smiTokname(c int) string {
	if c >= 1 && c-1 < len(smiToknames) {
		if smiToknames[c-1] != "" {
			return smiToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func smiStatname(s int) string {
	if s >= 0 && s < len(smiStatenames) {
		if smiStatenames[s] != "" {
			return smiStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func smiErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !smiErrorVerbose {
		return "syntax error"
	}

	for _, e := range smiErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + smiTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := smiPact[state]
	for tok := TOKSTART; tok-1 < len(smiToknames); tok++ {
		if n := base + tok; n >= 0 && n < smiLast && smiChk[smiAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if smiDef[state] == -2 {
		i := 0
		for smiExca[i] != -1 || smiExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; smiExca[i] >= 0; i += 2 {
			tok := smiExca[i]
			if tok < TOKSTART || smiExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if smiExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += smiTokname(tok)
	}
	return res
}

func smilex1(lex smiLexer, lval *smiSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = smiTok1[0]
		goto out
	}
	if char < len(smiTok1) {
		token = smiTok1[char]
		goto out
	}
	if char >= smiPrivate {
		if char < smiPrivate+len(smiTok2) {
			token = smiTok2[char-smiPrivate]
			goto out
		}
	}
	for i := 0; i < len(smiTok3); i += 2 {
		token = smiTok3[i+0]
		if token == char {
			token = smiTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = smiTok2[1] /* unknown char */
	}
	if smiDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", smiTokname(token), uint(char))
	}
	return char, token
}

func smiParse(smilex smiLexer) int {
	return smiNewParser().Parse(smilex)
}

func (smircvr *smiParserImpl) Parse(smilex smiLexer) int {
	var smin int
	var smiVAL smiSymType
	var smiDollar []smiSymType
	_ = smiDollar // silence set and not used
	smiS := smircvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	smistate := 0
	smircvr.char = -1
	smitoken := -1 // smircvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		smistate = -1
		smircvr.char = -1
		smitoken = -1
	}()
	smip := -1
	goto smistack

ret0:
	return 0

ret1:
	return 1

smistack:
	/* put a state and value onto the stack */
	if smiDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", smiTokname(smitoken), smiStatname(smistate))
	}

	smip++
	if smip >= len(smiS) {
		nyys := make([]smiSymType, len(smiS)*2)
		copy(nyys, smiS)
		smiS = nyys
	}
	smiS[smip] = smiVAL
	smiS[smip].yys = smistate

sminewstate:
	smin = smiPact[smistate]
	if smin <= smiFlag {
		goto smidefault /* simple state */
	}
	if smircvr.char < 0 {
		smircvr.char, smitoken = smilex1(smilex, &smircvr.lval)
	}
	smin += smitoken
	if smin < 0 || smin >= smiLast {
		goto smidefault
	}
	smin = smiAct[smin]
	if smiChk[smin] == smitoken { /* valid shift */
		smircvr.char = -1
		smitoken = -1
		smiVAL = smircvr.lval
		smistate = smin
		if Errflag > 0 {
			Errflag--
		}
		goto smistack
	}

smidefault:
	/* default state action */
	smin = smiDef[smistate]
	if smin == -2 {
		if smircvr.char < 0 {
			smircvr.char, smitoken = smilex1(smilex, &smircvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if smiExca[xi+0] == -1 && smiExca[xi+1] == smistate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			smin = smiExca[xi+0]
			if smin < 0 || smin == smitoken {
				break
			}
		}
		smin = smiExca[xi+1]
		if smin < 0 {
			goto ret0
		}
	}
	if smin == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			smilex.Error(smiErrorMessage(smistate, smitoken))
			Nerrs++
			if smiDebug >= 1 {
				__yyfmt__.Printf("%s", smiStatname(smistate))
				__yyfmt__.Printf(" saw %s\n", smiTokname(smitoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for smip >= 0 {
				smin = smiPact[smiS[smip].yys] + smiErrCode
				if smin >= 0 && smin < smiLast {
					smistate = smiAct[smin] /* simulate a shift of "error" */
					if smiChk[smistate] == smiErrCode {
						goto smistack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if smiDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", smiS[smip].yys)
				}
				smip--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if smiDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", smiTokname(smitoken))
			}
			if smitoken == smiEofCode {
				goto ret1
			}
			smircvr.char = -1
			smitoken = -1
			goto sminewstate /* try again in the same state */
		}
	}

	/* reduction by production smin */
	if smiDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", smin, smiStatname(smistate))
	}

	smint := smin
	smipt := smip
	_ = smipt // guard against "declared and not used"

	smip -= smiR2[smin]
	// smip is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if smip+1 >= len(smiS) {
		nyys := make([]smiSymType, len(smiS)*2)
		copy(nyys, smiS)
		smiS = nyys
	}
	smiVAL = smiS[smip+1]

	/* consult goto table to find next state */
	smin = smiR1[smin]
	smig := smiPgo[smin]
	smij := smig + smiS[smip].yys + 1

	if smij >= smiLast {
		smistate = smiAct[smig]
	} else {
		smistate = smiAct[smij]
		if smiChk[smistate] != -smin {
			smistate = smiAct[smig]
		}
	}
	// dummy call; replaced with literal code
	switch smint {

	case 2:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:359
		{
		}
	case 4:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:364
		{
		}
	case 5:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:379
		{
			m := Module{Name: smiDollar[1].id, Imports: smiDollar[7].impList, Nodes: smiDollar[8].nodeList}
			setModule(&smilex, &m)
		}
	case 6:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:386
		{
		}
	case 7:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:388
		{
		}
	case 8:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:392
		{
		}
	case 9:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:394
		{
		}
	case 11:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:402
		{
			smiVAL.impList = []Import{}
		}
	case 12:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:408
		{
			smiVAL.impList = smiDollar[2].impList
		}
	case 13:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:414
		{
		}
	case 14:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:416
		{
		}
	case 15:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:419
		{
		}
	case 17:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:424
		{
			smiVAL.impList = []Import{}
		}
	case 18:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:430
		{
			smiVAL.impList = []Import{smiDollar[1].imp}
		}
	case 19:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:434
		{
			smiVAL.impList = append(smiDollar[1].impList, smiDollar[2].imp)
		}
	case 20:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:442
		{
			smiVAL.imp = Import{From: smiDollar[3].id, Symbols: smiDollar[1].idList}
		}
	case 21:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:448
		{
			smiVAL.idList = []string{smiDollar[1].id}
		}
	case 22:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:452
		{
			smiVAL.idList = append(smiDollar[1].idList, smiDollar[3].id)
		}
	case 26:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:470
		{
		}
	case 27:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:472
		{
		}
	case 51:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:509
		{
		}
	case 52:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:511
		{
		}
	case 53:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:515
		{
			if smiDollar[1].node.Type != NodeNotSupported {
				smiVAL.nodeList = []Node{smiDollar[1].node}
			} else {
				smiVAL.nodeList = []Node{}
			}
		}
	case 54:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:523
		{
			if smiDollar[2].node.Type != NodeNotSupported {
				smiVAL.nodeList = append(smiDollar[1].nodeList, smiDollar[2].node)
			}
		}
	case 55:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:531
		{
		}
	case 56:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:534
		{
		}
	case 57:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:537
		{
		}
	case 58:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:540
		{
		}
	case 59:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:543
		{
		}
	case 60:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:546
		{
		}
	case 61:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:549
		{
		}
	case 62:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:552
		{
		}
	case 63:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:555
		{
		}
	case 64:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:558
		{
		}
	case 65:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:561
		{
		}
	case 66:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:564
		{
		}
	case 67:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:567
		{
		}
	case 68:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:577
		{
		}
	case 69:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:580
		{
		}
	case 70:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:584
		{
		}
	case 71:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:588
		{
			smiVAL.id = smiDollar[1].id
		}
	case 72:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:589
		{
			smiVAL.id = smiDollar[1].id
		}
	case 73:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:590
		{
			smiVAL.id = smiDollar[1].id
		}
	case 74:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:591
		{
			smiVAL.id = smiDollar[1].id
		}
	case 75:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:592
		{
			smiVAL.id = smiDollar[1].id
		}
	case 76:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:593
		{
			smiVAL.id = smiDollar[1].id
		}
	case 77:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:594
		{
			smiVAL.id = smiDollar[1].id
		}
	case 78:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:595
		{
			smiVAL.id = smiDollar[1].id
		}
	case 79:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:596
		{
			smiVAL.id = smiDollar[1].id
		}
	case 80:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:597
		{
			smiVAL.id = smiDollar[1].id
		}
	case 81:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:601
		{
		}
	case 82:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:605
		{
		}
	case 83:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:613
		{
		}
	case 84:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:617
		{
		}
	case 85:
		smiDollar = smiS[smipt-7 : smipt+1]
//line smi.y:624
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeObjectID, IDs: smiDollar[6].subidList}
			/*
				for i := 1; i <= 6; i++ {      //---show all parsing information
					__yyfmt__.Printf( "[%d]: %v\n", i, smiDollar[i]);
				}
			*/
		}
	case 86:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:633
		{
		}
	case 87:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:636
		{
		}
	case 88:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:641
		{
		}
	case 89:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:644
		{
		}
	case 90:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:647
		{
		}
	case 92:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:653
		{
		}
	case 103:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:674
		{
		}
	case 104:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:677
		{
		}
	case 105:
		smiDollar = smiS[smipt-7 : smipt+1]
//line smi.y:682
		{
		}
	case 106:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:686
		{
		}
	case 107:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:689
		{
		}
	case 108:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:695
		{
		}
	case 109:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:705
		{
		}
	case 110:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:711
		{
		}
	case 111:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:716
		{
		}
	case 112:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:719
		{
		}
	case 113:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:730
		{
		}
	case 114:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:735
		{
		}
	case 115:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:738
		{
		}
	case 116:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:744
		{
		}
	case 117:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:747
		{
		}
	case 118:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:750
		{
		}
	case 119:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:755
		{
		}
	case 120:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:758
		{
		}
	case 121:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:763
		{
		}
	case 122:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:766
		{
		}
	case 123:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:777
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeNotification, Status: smiDollar[4].id, Description: smiDollar[6].text, IDs: smiDollar[10].subidList} //---support more properties of mib object
			/*
				for i := 1; i <= 10; i++ {      //---show all parsing information
					__yyfmt__.Printf( "[%d]: %v\n", i, smiDollar[i]);
				}
			*/
		}
	case 124:
		smiDollar = smiS[smipt-21 : smipt+1]
//line smi.y:798
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeNotification, Syntax: smiDollar[4].id, Access: smiDollar[8].id, Status: smiDollar[10].id, Description: smiDollar[12].text, IDs: smiDollar[20].subidList} //---support more properties of mib object
			/*
				for i := 1; i <= 20; i++ {      //---show all parsing information
					__yyfmt__.Printf( "[%d]: %v\n", i, smiDollar[i]);
				}
			*/
		}
	case 125:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:804
		{
		}
	case 126:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:807
		{
		}
	case 127:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:812
		{
		}
	case 128:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:815
		{
		}
	case 129:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:822
		{
		}
	case 130:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:827
		{
		}
	case 131:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:830
		{
		}
	case 132:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:835
		{
		}
	case 133:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:838
		{
		}
	case 134:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:843
		{
		}
	case 135:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:848
		{
		}
	case 136:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:851
		{
		}
	case 137:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:855
		{
		}
	case 138:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:858
		{
		}
	case 139:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:861
		{
		}
	case 140:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:865
		{
		}
	case 141:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:869
		{
		}
	case 142:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:872
		{
		}
	case 143:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:876
		{
		}
	case 144:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:879
		{
		}
	case 145:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:881
		{
		}
	case 146:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:885
		{
		}
	case 147:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:888
		{
		}
	case 148:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:890
		{
		}
	case 149:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:895
		{
		}
	case 150:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:898
		{
		}
	case 151:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:900
		{
		}
	case 152:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:904
		{
		}
	case 153:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:906
		{
		}
	case 154:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:910
		{
		}
	case 155:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:913
		{
		}
	case 156:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:918
		{
		}
	case 157:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:922
		{
		}
	case 158:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:925
		{
		}
	case 159:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:927
		{
		}
	case 160:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:931
		{
		}
	case 161:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:934
		{
		}
	case 162:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:939
		{
		}
	case 163:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:945
		{
		}
	case 164:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:948
		{
		}
	case 165:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:950
		{
		}
	case 166:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:953
		{
		}
	case 167:
		smiDollar = smiS[smipt-12 : smipt+1]
//line smi.y:964
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeNotification, Status: smiDollar[5].id, Description: smiDollar[9].text, IDs: smiDollar[11].subidList} //---support more properties of mib object
			/*
				for i := 1; i <= 11; i++ {      //---show all parsing information
					__yyfmt__.Printf( "[%d]: %v\n", i, smiDollar[i]);
				}
			*/
		}
	case 168:
		smiDollar = smiS[smipt-16 : smipt+1]
//line smi.y:979
		{
			smiVAL.node = Node{Label: smiDollar[1].id, Type: NodeNotification, Description: smiDollar[11].text, IDs: smiDollar[15].subidList} //---support more properties of mib object
			/*
				for i := 1; i <= 15; i++ {      //---show all parsing information
					__yyfmt__.Printf( "[%d]: %v\n", i, smiDollar[i]);
				}
			*/
		}
	case 169:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:985
		{
		}
	case 170:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:988
		{
		}
	case 171:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:993
		{
		}
	case 172:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:998
		{
		}
	case 173:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1001
		{
		}
	case 174:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1006
		{
		}
	case 175:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1009
		{
		}
	case 176:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1014
		{
		}
	case 177:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1017
		{
		}
	case 178:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1020
		{
		}
	case 179:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1023
		{
		}
	case 180:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1026
		{
		}
	case 181:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1029
		{
		}
	case 182:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1034
		{
		}
	case 183:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1036
		{
		}
	case 184:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1044
		{
		}
	case 185:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1046
		{
		}
	case 186:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1051
		{
		}
	case 187:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1060
		{
		}
	case 188:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1063
		{
		}
	case 189:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1066
		{
		}
	case 190:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1069
		{
		}
	case 191:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1072
		{
		}
	case 192:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1075
		{
		}
	case 193:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1078
		{
		}
	case 194:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1081
		{
		}
	case 195:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1084
		{
		}
	case 196:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1087
		{
		}
	case 197:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1090
		{
		}
	case 198:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1093
		{
		}
	case 199:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1096
		{
		}
	case 200:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1099
		{
		}
	case 201:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1102
		{
		}
	case 202:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1105
		{
		}
	case 203:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1108
		{
		}
	case 204:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1111
		{
		}
	case 205:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1114
		{
		}
	case 206:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1120
		{
		}
	case 207:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1123
		{
		}
	case 208:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1126
		{
		}
	case 209:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1129
		{
		}
	case 210:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1132
		{
		}
	case 211:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1135
		{
		}
	case 212:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1138
		{
		}
	case 213:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1141
		{
		}
	case 214:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1160
		{
		}
	case 215:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1169
		{
		}
	case 216:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1172
		{
		}
	case 217:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1175
		{
		}
	case 218:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1178
		{
		}
	case 219:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1183
		{
		}
	case 220:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1186
		{
		}
	case 221:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1189
		{
		}
	case 222:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1192
		{
		}
	case 223:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1195
		{
		}
	case 224:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1198
		{
		}
	case 225:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1201
		{
		}
	case 226:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1204
		{
		}
	case 227:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1207
		{
		}
	case 228:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1210
		{
		}
	case 229:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1213
		{
		}
	case 230:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1216
		{
		}
	case 231:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1219
		{
		}
	case 232:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1222
		{
		}
	case 233:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1225
		{
		}
	case 234:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1228
		{
		}
	case 235:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1231
		{
		}
	case 236:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1240
		{
		}
	case 237:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1243
		{
		}
	case 238:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1246
		{
		}
	case 239:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1249
		{
		}
	case 240:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1252
		{
		}
	case 241:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1255
		{
		}
	case 242:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1258
		{
		}
	case 243:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1261
		{
		}
	case 244:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1264
		{
		}
	case 245:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1269
		{
		}
	case 246:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1272
		{
		}
	case 247:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1275
		{
		}
	case 248:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1278
		{
		}
	case 249:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1291
		{
		}
	case 250:
		smiDollar = smiS[smipt-6 : smipt+1]
//line smi.y:1301
		{
		}
	case 251:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1306
		{
		}
	case 252:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1309
		{
		}
	case 253:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1314
		{
		}
	case 254:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1317
		{
		}
	case 255:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1322
		{
		}
	case 256:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1325
		{
		}
	case 257:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1328
		{
		}
	case 258:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1331
		{
		}
	case 259:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1334
		{
		}
	case 260:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1337
		{
		}
	case 261:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1342
		{
		}
	case 262:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1347
		{
		}
	case 263:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1350
		{
		}
	case 264:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1355
		{
		}
	case 265:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1358
		{
		}
	case 266:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1363
		{
		}
	case 267:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1366
		{
		}
	case 268:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1371
		{
		}
	case 269:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1376
		{
		}
	case 270:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1381
		{
		}
	case 271:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1384
		{
		}
	case 272:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1389
		{
		}
	case 273:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1392
		{
		}
	case 274:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1397
		{
		}
	case 275:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1402
		{
		}
	case 276:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1405
		{
		}
	case 277:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1408
		{
		}
	case 278:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1411
		{
		}
	case 279:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1414
		{
		}
	case 280:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1417
		{
		}
	case 281:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1422
		{
		}
	case 282:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1425
		{
		}
	case 283:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1428
		{
		}
	case 284:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1433
		{
		}
	case 285:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1436
		{
		}
	case 286:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1441
		{
		}
	case 287:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1444
		{
		}
	case 288:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1449
		{
		}
	case 289:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1454
		{
		}
	case 290:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1459
		{
		}
	case 291:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1462
		{
		}
	case 292:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1466
		{
		}
	case 293:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1468
		{
		}
	case 294:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1473
		{
		}
	case 295:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1475
		{
		}
	case 296:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1479
		{
		}
	case 297:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1482
		{
		}
	case 298:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1487
		{
		}
	case 299:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1492
		{
		}
	case 300:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1497
		{
		}
	case 301:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1500
		{
		}
	case 302:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1504
		{
		}
	case 303:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1506
		{
		}
	case 304:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1510
		{
		}
	case 305:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1512
		{
		}
	case 306:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1516
		{
		}
	case 307:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1519
		{
		}
	case 308:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1524
		{
		}
	case 309:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1527
		{
		}
	case 310:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1532
		{
		}
	case 311:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1537
		{
		}
	case 312:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1540
		{
		}
	case 313:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1545
		{
		}
	case 314:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1550
		{
		}
	case 315:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1555
		{
		}
	case 316:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1558
		{
		}
	case 317:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1563
		{
		}
	case 318:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1568
		{
		}
	case 319:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1573
		{
		}
	case 320:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1578
		{
		}
	case 321:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1584
		{
			smiVAL.subidList = []SubID{smiDollar[1].subid}
		}
	case 322:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1589
		{
			smiVAL.subidList = append(smiDollar[1].subidList, smiDollar[2].subid)
		}
	case 323:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1597
		{
			smiVAL.subid = SubID{ID: -1, Label: smiDollar[1].id}
		}
	case 324:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1601
		{
			smiVAL.subid = SubID{ID: int(smiDollar[1].unsigned32)}
		}
	case 325:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1605
		{
			smiVAL.subid = SubID{int(smiDollar[3].unsigned32), smiDollar[1].id}
		}
	case 326:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1611
		{
		}
	case 327:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1615
		{
		}
	case 328:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1617
		{
		}
	case 329:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1621
		{
		}
	case 330:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1623
		{
		}
	case 331:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1627
		{
		}
	case 332:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1630
		{
		}
	case 333:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:1635
		{
		}
	case 334:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1639
		{
		}
	case 335:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1644
		{
		}
	case 336:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1647
		{
		}
	case 337:
		smiDollar = smiS[smipt-9 : smipt+1]
//line smi.y:1652
		{
		}
	case 338:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1656
		{
		}
	case 339:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1661
		{
		}
	case 340:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1664
		{
		}
	case 341:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1668
		{
		}
	case 342:
		smiDollar = smiS[smipt-15 : smipt+1]
//line smi.y:1673
		{
		}
	case 343:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1678
		{
		}
	case 344:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1683
		{
		}
	case 345:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1686
		{
		}
	case 346:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1691
		{
		}
	case 347:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1695
		{
		}
	case 348:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1700
		{
		}
	case 349:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1703
		{
		}
	case 350:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1706
		{
		}
	case 351:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1711
		{
		}
	case 352:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1714
		{
		}
	case 353:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1719
		{
		}
	case 354:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1722
		{
		}
	case 355:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1727
		{
		}
	case 356:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1732
		{
		}
	case 357:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1735
		{
		}
	case 358:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1740
		{
		}
	case 359:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1743
		{
		}
	case 360:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1748
		{
		}
	case 361:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1751
		{
		}
	case 362:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1756
		{
		}
	case 363:
		smiDollar = smiS[smipt-5 : smipt+1]
//line smi.y:1760
		{
		}
	case 364:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1765
		{
		}
	case 365:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1772
		{
		}
	case 366:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1777
		{
		}
	case 367:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1780
		{
		}
	case 368:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1785
		{
		}
	case 369:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1788
		{
		}
	case 370:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1793
		{
		}
	case 371:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1798
		{
		}
	case 372:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1801
		{
		}
	case 373:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1804
		{
		}
	case 374:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1809
		{
		}
	case 375:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1812
		{
		}
	case 376:
		smiDollar = smiS[smipt-10 : smipt+1]
//line smi.y:1817
		{
		}
	case 377:
		smiDollar = smiS[smipt-17 : smipt+1]
//line smi.y:1822
		{
		}
	case 378:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1827
		{
		}
	case 379:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1829
		{
		}
	case 380:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1833
		{
		}
	case 381:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1835
		{
		}
	case 382:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1839
		{
		}
	case 383:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1843
		{
		}
	case 384:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1848
		{
		}
	case 385:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1851
		{
		}
	case 386:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1856
		{
		}
	case 387:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1861
		{
		}
	case 388:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1864
		{
		}
	case 389:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1869
		{
		}
	case 390:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1871
		{
		}
	case 391:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1875
		{
		}
	case 392:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1877
		{
		}
	case 393:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1881
		{
		}
	case 394:
		smiDollar = smiS[smipt-8 : smipt+1]
//line smi.y:1888
		{
		}
	case 395:
		smiDollar = smiS[smipt-11 : smipt+1]
//line smi.y:1891
		{
		}
	case 396:
		smiDollar = smiS[smipt-2 : smipt+1]
//line smi.y:1896
		{
		}
	case 397:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1898
		{
		}
	case 398:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1902
		{
		}
	case 399:
		smiDollar = smiS[smipt-4 : smipt+1]
//line smi.y:1907
		{
		}
	case 400:
		smiDollar = smiS[smipt-0 : smipt+1]
//line smi.y:1910
		{
		}
	case 401:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1914
		{
		}
	case 402:
		smiDollar = smiS[smipt-3 : smipt+1]
//line smi.y:1916
		{
		}
	case 403:
		smiDollar = smiS[smipt-1 : smipt+1]
//line smi.y:1920
		{
		}
	}
	goto smistack /* stack new state and value */
}
